version: '3.4'

services:
  pethealthmonitor.producer:
    image: ${DOCKER_REGISTRY-}pethealthmonitorproducer
    build:
      context: .
      dockerfile: PetHealthMonitor.Producer/Dockerfile
    ports:
      - "63549:443"
      - "63550:80"

  pethealthmonitor.consumer:
    image: ${DOCKER_REGISTRY-}pethealthmonitorconsumer
    build:
      context: .
      dockerfile: PetHealthMonitor.Consumer/Dockerfile
  pethealthmonitor-mq:
    image: rabbitmq:management
    container_name: PetHealthMonitor.RabbitMq
    hostname: pethealth-mq
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"

  pethealthmonitor.function.consumer:
    image: ${DOCKER_REGISTRY-}pethealthmonitorfunctionconsumer
    build:
      context: .
      dockerfile: PetHealthMonitor.Function.Consumer/Dockerfile

