apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pethealthmonitor-producer
  name: pethealthmonitor-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pethealthmonitor-producer
  template:
    metadata:
      labels:
        app: pethealthmonitor-producer
    spec:
      containers:
        - name: pethealthmonitor-producer
          image: andrademm/pethealthmonitorproducer:latest
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_URLS
              value: http://+:80
            - name: ASPNETCORE_ENVIRONMENT
              value: "Development"
          resources:
            limits:
              cpu: "1"
              memory: "512Mi"
            requests:
              cpu: "0.5"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: pethealthmonitor-producer
spec:
  ports:
  - port: 8080
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: pethealthmonitor-producer
  type: LoadBalancer