apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pethealth-mq
  name: pethealth-mq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pethealth-mq
  template:
    metadata:
      labels:
        app: pethealth-mq
    spec:
      containers:
        - name: pethealth-mq
          image: rabbitmq:management
          ports:
          - containerPort: 5672
          - containerPort: 15672
          env:
            - name: RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-credentials
                  key: username
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-credentials
                  key: password
            - name: RABBITMQ_NODENAME
              value: "pethealth-mq"
          resources:
            limits:
              cpu: "1"
              memory: "512Mi"
            requests:
              cpu: "0.5"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: pethealth-mq
spec:
  ports:
  - port: 15672
    targetPort: 15672
    protocol: TCP
    name: rabbitmqmanagement
  - port: 5672
    targetPort: 5672
    protocol: TCP
    name: amqp
  selector:
    app: pethealth-mq
  type: LoadBalancer